project:
  type: website
  output-dir: docs

website:
  title: "Konfigurasi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bangtedy
      - icon: twitter
        href: https://twitter.com/t_hlb
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

